import type { Metadata } from "next";
import { Playpen_Sans } from "next/font/google";
import "./globals.css";

const PlaypenSans = Playpen_Sans({
  subsets: ["latin"],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={PlaypenSans.className}>{children}</body>
    </html>
  );
}
