import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from "@/theme";
import NavContainer from "@/components/Nav/NavContainer";
import AppContextProvider from "@/global state management/AppContextProvider";
import UserDrawerContainer from "@/components/UserDrawer/UserDrawerContainer";
import { CssBaseline } from "@mui/material";
import { AuthContextProvider } from "@/Auth/AuthContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <AppContextProvider>
              <AuthContextProvider>
                <NavContainer/>
                <UserDrawerContainer/>
                {children}
              </AuthContextProvider>
            </AppContextProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
